### ISSUE TITLE
Hidden libraries

### ISSUE THREAD

**Issue by DouglasHennrich** [magnatronus/star-demo-es6#1]
Can you show us how did you achieve this JSX method showing us your libraries? Nice work 👏

**Comment by magnatronus** [comment]
Hi,
The way I tried to do this was really trial and error, by starting off with a very simple JSX component and seeing what the Babel transpiler did with it.

for example:

``` javascript
import React from '/system/tilib';
import { Window, Label } from '/system/tilib-ui';

// example JSX component
const Example = () => {
  return (
    <Window style={styles.windowStyle}>
      <Label style={styles.labelStyle}>My Label</Label>
    </Window>
  );
}
```
This gets converted into a series of **React.createElement** calls.  So in another library (/system/tilib)  I created my own createElement method as follows:

``` javascript 
export default = {

  // Our Version of React createElement
  createElement( element, options, ...children){

    // element is the UI element (as defined in the tilib-ui module)

    // options are what is passed to the element ( i.e. styles etc.)

    // ... children are the child elements they could be:
    // * UI elements in case of window it would be the Label component
    // * String - in case of the Label component it would be "My Label"
    // * Array - not shown here but possibly in the case of something like a tableview it could be tableviewrows etc.

    // if there are any UI elements as children they have already been created and are passed in as reference
   
  }

};
```

This all gets very complicated as some UI elements need to be created before others, some afterwards etc, etc. So I had to put logic in to build the component list  
and then assemble once all the createElement calls had run.

The issue here was trying to make the Titanium UI generate as though it was a React-Native UI, which was not ideal trying to 'bend it' to fit.

When I have some free time I will upload into a different repo the JSX stuff.
